name: Check Tests and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: yarn install
      env:
        REACT_APP_OKTA_CLIENT_ID: ${{ secrets.DEV_OKTA_CLIENT_ID }}
        REACT_APP_OKTA_ISSUER: ${{ secrets.DEV_OKTA_ISSUER }}
        REACT_APP_OKTA_REDIRECT: ${{ secrets.DEV_OKTA_REDIRECT }}
        REACT_APP_DRIVER_PAYOUT_API: ${{ secrets.DEV_DRIVER_PAYOUT_API }}

    - name: Run the tests
      run: yarn test

    - name: Build
      run: yarn run build

    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx